export interface SanityCourseDocument {
  _id: string;
  _type: 'course';
  id: string; // code like F1, T2, A1
  code: string;
  title: string;
  slug: { current: string };
  track: 'Fundamentals' | 'Technicals' | 'Automation';
  level: string;
  description: string;
  lessonsCount: number;
  duration: string;
  coverArtType: 'bars' | 'candlestick' | 'network';
  recommended?: boolean;
}

export const SANITY_COURSES: SanityCourseDocument[] = [
  {
    _id: 'course-f1',
    _type: 'course',
    id: 'F1',
    code: 'F1',
    title: 'Market basics',
    slug: { current: 'market-basics' },
    track: 'Fundamentals',
    level: 'Beginner',
    description: 'How currencies, gold, oil, indices, stocks and crypto are priced, and who moves them.',
    lessonsCount: 5,
    duration: '45 min',
    coverArtType: 'bars',
  },
  {
    _id: 'course-f2',
    _type: 'course',
    id: 'F2',
    code: 'F2',
    title: 'Reading the economic calendar',
    slug: { current: 'reading-the-economic-calendar' },
    track: 'Fundamentals',
    level: 'Beginner',
    description: 'Forecast, actual, previous and impact levels, and how to plan your week around them.',
    lessonsCount: 5,
    duration: '50 min',
    coverArtType: 'bars',
  },
  {
    _id: 'course-f3',
    _type: 'course',
    id: 'F3',
    code: 'F3',
    title: 'Inflation, jobs and growth',
    slug: { current: 'inflation-jobs-and-growth' },
    track: 'Fundamentals',
    level: 'Beginner to Intermediate',
    description: 'CPI, PCE, payrolls and GDP: what each one measures and why markets care.',
    lessonsCount: 5,
    duration: '1h 10m',
    coverArtType: 'bars',
  },
  {
    _id: 'course-f4',
    _type: 'course',
    id: 'F4',
    code: 'F4',
    title: 'Central banks and interest rates',
    slug: { current: 'central-banks-and-interest-rates' },
    track: 'Fundamentals',
    level: 'Intermediate',
    description: 'Rate decisions, hawkish versus dovish, and how guidance moves currencies.',
    lessonsCount: 6,
    duration: '1h 20m',
    coverArtType: 'bars',
  },
  {
    _id: 'course-f5',
    _type: 'course',
    id: 'F5',
    code: 'F5',
    title: 'Geopolitics and risk sentiment',
    slug: { current: 'geopolitics-and-risk-sentiment' },
    track: 'Fundamentals',
    level: 'Intermediate',
    description: 'Safe havens, oil shocks, and why markets switch between risk-on and risk-off.',
    lessonsCount: 5,
    duration: '55 min',
    coverArtType: 'bars',
  },
  {
    _id: 'course-f6',
    _type: 'course',
    id: 'F6',
    code: 'F6',
    title: 'Trading the news safely',
    slug: { current: 'trading-the-news-safely' },
    track: 'Fundamentals',
    level: 'Intermediate',
    description: 'Spreads, slippage and volatility around releases, and when waiting is the better trade.',
    lessonsCount: 5,
    duration: '1h 00m',
    coverArtType: 'bars',
  },
  {
    _id: 'course-t1',
    _type: 'course',
    id: 'T1',
    code: 'T1',
    title: 'Candlesticks and timeframes',
    slug: { current: 'candlesticks-and-timeframes' },
    track: 'Technicals',
    level: 'Beginner',
    description: 'Read price action and choose timeframes that fit your schedule.',
    lessonsCount: 5,
    duration: '45 min',
    coverArtType: 'candlestick',
  },
  {
    _id: 'course-t2',
    _type: 'course',
    id: 'T2',
    code: 'T2',
    title: 'Market structure',
    slug: { current: 'market-structure' },
    track: 'Technicals',
    level: 'Beginner',
    description: 'Trends, ranges, support and resistance, and breakouts that hold versus ones that fail.',
    lessonsCount: 6,
    duration: '1h 15m',
    coverArtType: 'candlestick',
  },
  {
    _id: 'course-t3',
    _type: 'course',
    id: 'T3',
    code: 'T3',
    title: 'Indicators that matter',
    slug: { current: 'indicators-that-matter' },
    track: 'Technicals',
    level: 'Intermediate',
    description: 'Moving averages, RSI, ATR and volume: what they show and what they hide.',
    lessonsCount: 5,
    duration: '50 min',
    coverArtType: 'candlestick',
  },
  {
    _id: 'course-t4',
    _type: 'course',
    id: 'T4',
    code: 'T4',
    title: 'Building a trading plan',
    slug: { current: 'building-a-trading-plan' },
    track: 'Technicals',
    level: 'Intermediate',
    description: 'Entries, exits and journaling, written down before you risk a cent.',
    lessonsCount: 5,
    duration: '1h 05m',
    coverArtType: 'candlestick',
  },
  {
    _id: 'course-t5',
    _type: 'course',
    id: 'T5',
    code: 'T5',
    title: 'Risk management',
    slug: { current: 'risk-management' },
    track: 'Technicals',
    level: 'All levels',
    description: 'Position sizing, stop placement and surviving drawdowns.',
    lessonsCount: 5,
    duration: '1h 00m',
    coverArtType: 'candlestick',
  },
  {
    _id: 'course-a1',
    _type: 'course',
    id: 'A1',
    code: 'A1',
    title: 'Programming for traders',
    slug: { current: 'programming-for-traders' },
    track: 'Automation',
    level: 'Beginner',
    description: 'Python and MQL5 basics, taught with trading examples from day one.',
    lessonsCount: 6,
    duration: '1h 30m',
    coverArtType: 'network',
  },
  {
    _id: 'course-a2',
    _type: 'course',
    id: 'A2',
    code: 'A2',
    title: 'Build your first Expert Advisor',
    slug: { current: 'build-your-first-expert-advisor' },
    track: 'Automation',
    level: 'Intermediate',
    description: 'Write, compile and run an MT5 trading robot on a demo account.',
    lessonsCount: 6,
    duration: '1h 45m',
    coverArtType: 'network',
  },
  {
    _id: 'course-a3',
    _type: 'course',
    id: 'A3',
    code: 'A3',
    title: 'Custom indicators',
    slug: { current: 'custom-indicators' },
    track: 'Automation',
    level: 'Intermediate',
    description: 'Create your own indicators in MQL5 and Pine Script.',
    lessonsCount: 5,
    duration: '1h 10m',
    coverArtType: 'network',
  },
  {
    _id: 'course-a4',
    _type: 'course',
    id: 'A4',
    code: 'A4',
    title: 'Multi-market scanners',
    slug: { current: 'multi-market-scanners' },
    track: 'Automation',
    level: 'Advanced',
    description: 'Scan dozens of pairs, metals, indices and stocks for your setups at once.',
    lessonsCount: 5,
    duration: '1h 20m',
    coverArtType: 'network',
  },
  {
    _id: 'course-a5',
    _type: 'course',
    id: 'A5',
    code: 'A5',
    title: 'Backtesting the right way',
    slug: { current: 'backtesting-the-right-way' },
    track: 'Automation',
    level: 'Advanced',
    description: 'Data quality, overfitting, out-of-sample and walk-forward testing.',
    lessonsCount: 6,
    duration: '1h 35m',
    coverArtType: 'network',
    recommended: true,
  },
  {
    _id: 'course-a6',
    _type: 'course',
    id: 'A6',
    code: 'A6',
    title: 'Alerts and webhooks',
    slug: { current: 'alerts-and-webhooks' },
    track: 'Automation',
    level: 'Intermediate',
    description: 'Send TradingView and MT5 signals to Telegram, email or your own app.',
    lessonsCount: 5,
    duration: '1h 15m',
    coverArtType: 'network',
    recommended: true,
  },
  {
    _id: 'course-a7',
    _type: 'course',
    id: 'A7',
    code: 'A7',
    title: 'Risk and position-sizing automation',
    slug: { current: 'risk-and-position-sizing-automation' },
    track: 'Automation',
    level: 'Intermediate',
    description: 'Let code calculate lot sizes and enforce your risk limits every time.',
    lessonsCount: 5,
    duration: '1h 10m',
    coverArtType: 'network',
    recommended: true,
  },
  {
    _id: 'course-a8',
    _type: 'course',
    id: 'A8',
    code: 'A8',
    title: 'Automated trade journaling',
    slug: { current: 'automated-trade-journaling' },
    track: 'Automation',
    level: 'Beginner',
    description: 'Log every trade automatically and review your real statistics.',
    lessonsCount: 5,
    duration: '50 min',
    coverArtType: 'network',
    recommended: true,
  },
  {
    _id: 'course-a9',
    _type: 'course',
    id: 'A9',
    code: 'A9',
    title: 'Prop-firm rule guards',
    slug: { current: 'prop-firm-rule-guards' },
    track: 'Automation',
    level: 'Advanced',
    description: 'Automate daily-loss and maximum-drawdown limits so one bad day never ends an account.',
    lessonsCount: 6,
    duration: '1h 40m',
    coverArtType: 'network',
    recommended: true,
  },
  {
    _id: 'course-a10',
    _type: 'course',
    id: 'A10',
    code: 'A10',
    title: 'Using AI in trading research',
    slug: { current: 'using-ai-in-trading-research' },
    track: 'Automation',
    level: 'Advanced',
    description: 'Use AI to summarise news and test ideas without trusting it blindly.',
    lessonsCount: 5,
    duration: '1h 25m',
    coverArtType: 'network',
    recommended: true,
  },
];
